repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-added-large-files
    args: [--maxkb=2500]
  - id: check-ast
  - id: check-case-conflict
  - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-toml
  - id: check-yaml
  - id: end-of-file-fixer
    exclude: ^DATAWAREHOUSE/ || ^DATAFACTORY/
  - id: name-tests-test
    args: [--pytest-test-first]
  - id: no-commit-to-branch
    args: [--branch, develop, --branch, master, --branch, adf_release]
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
  - id: isort
    name: isort (python)
    args: ["--profile", "black"]
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.32.0
  hooks:
  - id: yapf
    additional_dependencies: [toml]
    args: [--style "google" ]
    exclude: ^DATAWAREHOUSE/
- repo: https://github.com/psf/black
  rev: 22.12.0
  hooks:
    - id: black
      args: [--line-length, '180']
- repo: https://github.com/PyCQA/flake8
  rev: 6.0.0
  hooks:
  - id: flake8
    args: [--docstring-convention, google]
    additional_dependencies: [flake8-bugbear, flake8-docstrings, pydocstyle==6.1.1]
    exclude: ^DATAWAREHOUSE/
- repo: https://github.com/pycqa/pylint
  rev: v2.16.0b1
  hooks:
  - id: pylint
    exclude: ^DATAWAREHOUSE/
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.991
  hooks:
    - id: mypy
      exclude: ^(DATAWAREHOUSE/)
      additional_dependencies: ["types-PyYAML", "types-requests"]
- repo: https://github.com/pycqa/bandit
  rev: 1.7.4
  hooks:
  - id: bandit
    files: src/
    args: [--skip, B608]
