trigger:
  - develop

variables:
  buildAgents: 'LocalPool'
  environment: dev
  templateFile: deployinfra.bicep
  serviceConnection: tetris-sp-${{ variables.environment }}
  resourceGroup: platform-tetris-${{ variables.environment }}
  storageAccountName: stract${{ variables.environment }}
  storageAccountSku: Standard_LRS
  storageAccountTier: Hot
  webAppServerName: platform-tetris-webapp-server-${{ variables.environment }}
  webAppServerSku: F1
  webAppServerSkuCapacity: 1
  webAppName: platform-tetris-webapp-${{ variables.environment }}
  webAppLinuxFxVersion: "Python|3.11"

stages:
- stage: Linting
  displayName: Linting
  pool: ${{ variables.buildAgents }}
  jobs:
  - job: PreCommitLinting
    displayName: Pre-Commit Linting
    steps:
      - checkout: self 
      - task: Bash@3
        displayName: 'Pre-Commit Linting'
        continueOnError: true
        inputs:
          targetType: 'inline'
          script: |
            set -eou pipefail
            trap exit 1 ERR
            python -m pip install pre-commit
            pre-commit install
            pre-commit run --all-files
          workingDirectory: 'platform'

- stage: DeployInfra
  dependsOn: Linting
  jobs:     
  - deployment: Infra
    environment: ${{ variables.environment }}
    pool: ${{ variables.buildAgents }}
    strategy:
      runOnce:
        deploy:
          steps:
          - download: current
          - task: AzureCLI@2
            displayName: Deploy
            inputs:
              azureSubscription: ${{ variables.serviceConnection }}
              failOnStandardError: true
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                if [[ $(az group exists -g ${{ variables.resourceGroup }}) == false ]]; then
                  az group create --name ${{ variables.resourceGroup }} --location uksouth
                fi

                OUTPUT=$(az deployment group create \
                  --resource-group ${{ variables.resourceGroup }} \
                  --template-file ${{ variables.templateFile }} \
                  --parameters storageAccountName=${{ variables.storageAccountName }} storageAccountSku=${{ variables.storageAccountSku }} storageAccountTier=${{ variables.storageAccountTier }} \
                    webAppServerName=${{ variables.webAppServerName }} webAppServerSku=${{ variables.webAppServerSku }} webAppServerSkuCapacity=${{ variables.webAppServerSkuCapacity }} \
                    webAppName=${{ variables.webAppName }} webAppLinuxFxVersion=${{ variables.webAppLinuxFxVersion }} \
                  --query properties.outputs
                )
                echo "##vso[task.setvariable variable=DEPLOYOUTPUT}]"$OUTPUT
              workingDirectory: 'platform/infra'
          - task: AzureCLI@2
            displayName: 'Test Infra'
            inputs:
              azureSubscription: ${{ variables.servicePrincipal }}
              scriptLocation: inlineScript
              inlineScript: |
                set -eou pipefail
                trap exit 1 ERR
                python -m venv venv
                venv/bin/pip install --upgrade pip setuptools wheel
                source venv/bin/activate
                pip install -r requirements.txt
                pytest -o junit_family=xunit2 --junitxml=test-infra.xml
                deactivate
                rm -rf venv
              workingDirectory: 'platform/infra/tests'
            env:
              DEPLOYOUTPUT: $(DEPLOYOUTPUT)
            continueOnError: true
          - task: PublishTestResults@2
            displayName: 'Publish Test results'
            inputs:
              testResultsFiles: '**/*.xml'
              searchFolder: 'platform/infra/tests'